### ISSUE TITLE
Heroku site unable to open

### ISSUE THREAD

**Issue by hoodboi2** [Astropeda/Asta-Md#12]
I can't deploy the boy using heroku. It's showing something saying there's a problem with app.json schema something like that I can't reach the part where I put my own information. I attached a screenshot for you to see.

 - Device: [Samsung A13]
 - OS: [Android 14 / [One UI 6.0]
 - Browser [Chrome]
![Screenshot_20240502_224729_Chrome](https://github.com/Astropeda/Asta-Md/assets/161243219/905c84b2-6d1b-4193-aa8e-16524feb79d2)

**Comment by Astropeda** [comment]
Error Fixed

**Comment by Toxicity404** [comment]
Same here too I'm experiencing same issues can't create an app on my heroku

**Comment by Astropeda** [comment]
Error Fixed man
