### ISSUE TITLE
WhatsApp functions Not working 

### ISSUE THREAD

**Issue by Astropeda** [Astropeda/Asta-Md#5]
This is caused by the session id not have my App Key State, it's from whiskeys sockets and I don't know what to do in this case, any one with solutions please message me 

2349027862116
Astropeda Team

**Comment by Riders004** [comment]
I'm not understand by the way is your bot based in suhail md ?

**Comment by Astropeda** [comment]
> I'm not understand by the way is your bot based in suhail md ?

What don't you understand, simply fork, deploy and run the bot that's all

**Comment by Astropeda** [comment]
never going to work
